### ISSUE TITLE
No sand, gravel, and clay in river

### ISSUE THREAD

**Issue by frank89722** [EwyBoy/OreTweaker#10]
Forge version: 36.1.4
OreTweaker version: 2.0.0

![image](https://user-images.githubusercontent.com/10683361/117548607-77ec6300-b068-11eb-910f-01e4be9caf02.png)
![image](https://user-images.githubusercontent.com/10683361/117548621-8c306000-b068-11eb-9dd6-dfad6842d0b2.png)

**Comment by EwyBoy** [comment]
Thanks for the report, I will look into a fix.

**Comment by EwyBoy** [comment]
Fixed in v2.0.1 https://www.curseforge.com/minecraft/mc-mods/ore-tweaker/files/3303589
Thanks for the report!

![2021-05-09_13 14 09](https://user-images.githubusercontent.com/5883716/117570397-3096be80-b0ca-11eb-85c9-1eff0275dde7.png)

**Comment by frank89722** [comment]
Thanks for your quick response and fix!

**Comment by EwyBoy** [comment]
This is now properly fixed due to the bug uncovered in #11 and #9 
Patch can be found here: https://www.curseforge.com/minecraft/mc-mods/ore-tweaker/files/3307868
