### ISSUE TITLE
[Bug] Relevant title here

### ISSUE THREAD

**Issue by Chouliam** [EwyBoy/OreTweaker#102]
###### **Minecraft Version**
> 1.18.2

###### **Forge Version**
> 40.2.4

###### **Mod Version**
> 4.4.6

###### **Describe the bug**
> cannot load ancient debris
###### **How to reproduce**
> Type here

###### **Link to [crashlog](https://gist.github.com/)** *[If Applicable]*
> Type here

###### **Screenshots / Images**
> Ctrl + V here

**Comment by Bebobobo** [comment]
feel free to reach out on discord directly https://discord.com/channels/305535757441826817/390890978980003840 or you can post the config file you are using for ancient debris as well as the filename of the mod being used.
