### ISSUE TITLE
[Feature] Make "filler" support Minecraft's Tag system

### ISSUE THREAD

**Issue by Souperhero** [EwyBoy/OreTweaker#12]
When customizing, I attemped to use an arry to list multiple types of stone, not just minecraft:stone.

Obviously, threw an error on start up expecting a string not an array. Possible feature suggestion? Otherwise we'd have to make multiple "ore"s for the same kind of ore using different fillers.

Thanks!

Caused by 0: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 340 column 18 path $.oreConfig[40].filler

    {
      "ore": "basicores:gold",
      "filler": ["minecraft:stone", "minecraft:granite", "minecraft:andesite", "minecraft:diorite", "create:dolomite", "create:weathered_limestone", "create:gabbro", "create:scoria"],
      "minY": 5,
      "maxY": 60,
      "maxVeinSize": 32,
      "spawnRate": 2,
      "biomeBlacklist": [],
      "biomeWhitelist": []
    }

**Comment by EwyBoy** [comment]
Yes, the filler does not currently support multiple entries. Vanilla Minecraft uses data tags for this so I either have to code my own custom ore feature for this to work or incorporate a tag system. I will look into both and see what works best for the end user-experience.

**Comment by TrashCasterMage** [comment]
I myself actually just came to this page to suggest tags as filler, and I'm glad to see I'm not the only one. Just letting us easily use the stones tag would be very helpful for those of us running Terraforged worlds, since I think right now there isn't a single mod out there that lets you use tags for filler blocks.

**Comment by EwyBoy** [comment]
Both this and #13 will be added in the next major update since the changes required to the json file will break compatibility with earlier versions.

**Comment by EwyBoy** [comment]
Added to Ore Tweaker 3.
