### ISSUE TITLE
[Feature] Make "spawnrate" support both count & chance

### ISSUE THREAD

**Issue by Souperhero** [EwyBoy/OreTweaker#13]
No code or crashlog for this one, but more of a question leading to a suggestion.

Does spawnRate of 1 mean that 1 ore vein will spawn per chunk? If so, how possible is it to use a float so that between 0 and 1 would mean 1 vein every x chunks.

so a .11 would mean 1 vein every 9 chunks?

**Comment by EwyBoy** [comment]
Hello, Souperhero. Thank you for your suggestion. This can certainly be done. The minecraft world gen currently have 2 main categories for spawning in stuff.
1. count (the one that is currently used)
2. chance (pretty much what you proposed)

My plan is to make it so if you use a number less then 1 like 0.88 it will be converted into chance else it would use the regular count for whole integer numbers like 6 and 9.

**Comment by EwyBoy** [comment]
Both this and #12 will be added in the next major update since the changes required to the json file will break compatibility with earlier versions.

**Comment by EwyBoy** [comment]
Added in 2.3.1 on both 1.17 and 1.16
