### ISSUE TITLE
[Bug] Mods with custom ore gen features can't be disabled

### ISSUE THREAD

**Issue by EwyBoy** [EwyBoy/OreTweaker#16]
Mod needs a safe way / or hardcoded dependency on mods to disable stuff like this

**Comment by Souperhero** [comment]
Workaround: 

disable ore spawn from any mod using a filler that doesn't naturally spawn like minecraft:gold_block, combined with minY maxY that makes sense.

    {
      "ore": "electrodynamics:oretin",
      "filler": "minecraft:gold_block",
      "minY": -1,
      "maxY": -1,
      "maxVeinSize": -1,
      "spawnRate": -1.0,
      "biomeBlacklist": [],
      "biomeWhitelist": []
    },
