### ISSUE TITLE
[1.9.4] OreTweaker not working?

### ISSUE THREAD

**Issue by MrAmericanMike** [EwyBoy/OreTweaker#2]
So I'm using the 1.0.0-1.9.4 version, and trying to tweak the way Andesite and other stones spawn, but it doesn't seam to work, I'm wondering if it's a bug or I'm doing something wrong.

I want Andesite to be able to spawn only from level 55 to 256. Shouldn't a config like this work for that?

PS: I just saw there was an update, gonna test that version.

```

"andesite tweaks" {
    # Set to true to enable custom ore generation for Andesite [default: false]
    B:"Custom OreGen: Andesite"=true

    # Set to true to disable vanilla generation of Andesite [default: false]
    B:"Disable Andesite"=false

    # Sets the maximum vein spawn level [Y-level] for Andesite [range: 1 ~ 256, default: 0]
    I:"Maximum Spawn Level: Andesite"=256

    # Sets the maximum vein size value for Andesite [range: 0 ~ 2147483647, default: 0]
    I:"Maximum Vein Size: Andesite"=0

    # Sets the minimum vein spawn level [Y-level] for Andesite [range: 1 ~ 256, default: 0]
    I:"Minimum Spawn Level: Andesite"=55

    # Sets the minimum vein size value for Andesite [range: 0 ~ 2147483647, default: 0]
    I:"Minimum Vein Size: Andesite"=0

    # Sets the spawn rate of the ore vein [Amount of veins per chunk] for Andesite [range: 0 ~ 2147483647, default: 0]
    I:"Spawn Rate: Andesite"=0
}
```

**Comment by MrAmericanMike** [comment]
Confirmed using the 1.0.1 version, also same problems. Andesite still generates

**Comment by EwyBoy** [comment]
Since your maximum and minimum vein size is equal to 0, the code reads it as the vein size as 0 aswell as the spawn rate of the Andesite is alos 0. You have to fill in all the values. 
I am currently reworking the mod to make it way more user friendly.

**Comment by Lanse505** [comment]
Just want to add "Spawn Rate: Andesite=0" means it will try to spawn 0 Veins per chunk :P

**Comment by TheCodedOne** [comment]
Just want to add, "HI MUM!" oh and also.. 0 = -_- really

**Comment by EwyBoy** [comment]
Also the vein size will be 0 times 0 witch is also 0

**Comment by Lanse505** [comment]
Also 

    # Set to true to disable vanilla generation of Andesite [default: false]
    B:"Disable Andesite"=false

Should be

    # Set to true to disable vanilla generation of Andesite [default: false]
    B:"Disable Andesite"=true

Since you want to replace Andesite Generation with your own custom one!

**Comment by TheCodedOne** [comment]
I have nothing productive to add to this issue!

**Comment by MrAmericanMike** [comment]
Thanks for the tips, gonna do some more testing ;)

**Comment by MrAmericanMike** [comment]
Nevermind me, I now realize, 0 is the config file default, I thought leaving it on 0 means "vanilla default" my bad :D

However, I now tried this and still no success. No Andesite anywhere.

`"andesite tweaks" {
    # Set to true to enable custom ore generation for Andesite [default: false]
    B:"Custom OreGen: Andesite"=true

    # Set to true to disable vanilla generation of Andesite [default: false]
    B:"Disable Andesite"=true

    # Sets the maximum vein spawn level [Y-level] for Andesite [range: 1 ~ 256, default: 0]
    I:"Maximum Spawn Level: Andesite"=75

    # Sets the maximum vein size value for Andesite [range: 0 ~ 2147483647, default: 0]
    I:"Maximum Vein Size: Andesite"=20

    # Sets the minimum vein spawn level [Y-level] for Andesite [range: 1 ~ 256, default: 0]
    I:"Minimum Spawn Level: Andesite"=45

    # Sets the minimum vein size value for Andesite [range: 0 ~ 2147483647, default: 0]
    I:"Minimum Vein Size: Andesite"=5

    # Sets the spawn rate of the ore vein [Amount of veins per chunk] for Andesite [range: 0 ~ 2147483647, default: 0]
    I:"Spawn Rate: Andesite"=20
}`

At this point I don't know where I'm wrong now, everything seams to be ok, I tried Spawn rate 2 and 20, nothing works. Vein sizes are set, Y max level down a lot also, and still nothing, it just wont generate Andesite.

http://i.imgur.com/uEPFUK5.png

I would appreciate anyone testing and sharing a working config to spawn Andesite only from any Y level and up. (Example 45 and higher)

Thanks a lot.

**Comment by EwyBoy** [comment]
Might be some other stuff causing the problem, I will look into it
