### ISSUE TITLE
[Compatibility] MOD-NAME

### ISSUE THREAD

**Issue by ValkRed** [EwyBoy/OreTweaker#21]
**Name of mod you want compatibility with?**
Mod name.

**Is your compatibility request related to a problem?**

**Describe the solution you'd like**
A clear and concise description of what you want the compatibility to accomplish.

**Additional context**
Add any other context or screenshots about the compatibility request here.

**Comment by ValkRed** [comment]
Sky’s ultimate ore mod by sky2playz
When the mod is enabled: I Disabled the ore generation, ex. 
"{
      "ore": "skys_ultimate_ore_mod:ruby_ore",
      "minY": -1,
      "maxY": -1,
      "maxVeinSize": -1,
      "spawnRate": -1
    },"
and so on and added that to OreTweaker.json
However, when I enter the Modpack and click SinglePlayer, it gives me the following error: 
The game crashed whilst mouseclicked event handler
Error: java.lang.IllegalStateException: failed to create a child event loop
When I disable the mod, the rest of the Modpack works just fine.
Could you fix it?
Thanks for your time!

**Comment by EwyBoy** [comment]
This is not a mod compatibility request this is a bug. Moved to new bug thread..

**Comment by EwyBoy** [comment]
https://github.com/EwyBoy/OreTweaker/issues/22
