### ISSUE TITLE
[Compatibility] Add a config option to only allow removing & replacing existing ore/stone gen when entries in the config exist.

### ISSUE THREAD

**Issue by Thombias** [EwyBoy/OreTweaker#23]
**Name of mod you want compatibility with?**
Basically every mod that adds ore and stone generation. But mostly Quark's stone types.

**Is your compatibility request related to a problem?**
Yes. When i configured the mod i noticed that it also removed all of Quarks stone generation. The weird thing is, when i added entries to let Ore Tweaker handle Quark stone generation they didn't even generate 99% of the time.

**Describe the solution you'd like**
I don't know how possible this is, but i'd like to have a config option or just some way to make Ore Tweaker only remove & replace existing ore/stone generation from vanilla or a mod if you actually added an entry with the ore/stone in the config. So if you for example have an entry with quark:limestone then the mod removes the generation from Quark only for that stone type, but if you have no entry for any vanilla or quark stone types, the mod should ignore them so they don't get removed. It would help a lot with improving the compatibility for this mod i think.

**Additional context**
I actually only need this mod to make ice and fire ores spawn in more fitting biomes and in higher quantites (seriously, copper is so freaking rare in that mod, like wtf?) but the problem is installing this mod disables everything. I need to add entries for literally everything and it seems the biomewhitelist function isn't working?
I entered the biomes like this ["minecraft:desert", atmospheric:dunes", etc.]
Feel free to tell me if i somehow made a mistake in the config without even noticing. Thanks in advance!

**Comment by EwyBoy** [comment]
Working on a solution for this.
Biome whitelist / blacklist only takes the biome name not the full resource location.
Use `desert` not ``minecraft:desert`

**Comment by Thombias** [comment]
Thank you so much! But do i still have to use the full resource location for modded biomes? Or would be "dunes" enough for the mod to detect the dunes biome added by the atmospheric mod?
I remember from my 1.12.2 modpack that some mods didn't require vanilla stuff to be entered like this "minecraft:zombie" or "minecraft:desert" and instead just "zombie" or "desert" was fine. Modded mobs and biomes still required the full name though "modid:mob" or "modid:biome". Is this still the case here?

**Comment by EwyBoy** [comment]
'dunes' will be enough and cover all dunes biomes added under that name.

**Comment by EwyBoy** [comment]
Added in Ore Tweaker 3.
