### ISSUE TITLE
[Compatibility] quark

### ISSUE THREAD

**Issue by TheGamersBrew** [EwyBoy/OreTweaker#24]
**Name of mod you want compatibility with?**
Mod name: Quark

**Is your compatibility request related to a problem?**
Issue is when I try to remove the spawning of the stone_speleothem the I get the error code that Oretweaker has failed to load correctly. (see picture)

**Describe the solution you'd like**
A clear and concise description of what you want the compatibility to accomplish.
Would like the compatibility to allow Ore Tweaker to be able to and and remove the different types speleothem out of the generation

**Additional context**
Add any other context or screenshots about the compatibility request here.

This is the way i'm trying to remove it.

`{
      "ore": "quark:stone_speleothem",
      "minY": -1,
      "maxY": -1,
      "maxVeinSize": -1,
      "spawnRate": -1.0,
    }`

![image](https://user-images.githubusercontent.com/77638191/124542764-99a86300-dde9-11eb-983d-c979339c1ad7.png)

**Comment by EwyBoy** [comment]
The problem is not compatibility with Quark but a syntax error in your JSON file..

**Comment by TheGamersBrew** [comment]
Did i write the code wrong then? Cause once i removed the working for the removal of speleothem it worked just fine.

**Comment by TheGamersBrew** [comment]
Closing issue as after further digging found with in Quark there is an option with in there config file to remove Speleothem.

**Comment by EwyBoy** [comment]
> Did i write the code wrong then? Cause once i removed the working for the removal of speleothem it worked just fine.

Ofc it worked once you removed it, cause you removed the syntax error. 
From what I can see you have a ',' at the last line of your JSON entry after spawnrate: -1.0.
Use a JSON validator to ensure you file is not malfunctioning.
