### ISSUE TITLE
[Compatibility] Immersive Engineering

### ISSUE THREAD

**Issue by TheGamersBrew** [EwyBoy/OreTweaker#25]
**Name of mod you want compatibility with?**
Mod name. Immersive Engineering

**Is your compatibility request related to a problem?**
There form of Copper and Silver ore is not being removed from world generation when using this mods ability to remove said ore.

**Describe the solution you'd like**
Would like to be able to use your mods ability to remove Immersive Engineering ore generation from the world

**Additional context**

![image](https://user-images.githubusercontent.com/77638191/124702864-d42c0180-deb6-11eb-834f-a5183cb1153f.png)

![image](https://user-images.githubusercontent.com/77638191/124702846-cb3b3000-deb6-11eb-8943-05217390df7a.png)

**Comment by Boolyman** [comment]
Did this get done?

**Comment by EwyBoy** [comment]
Not yet, but Immersive Engineerings ores can be turned off in the mods config file.

**Comment by EwyBoy** [comment]
Decided against doing compatibility requests and instead make ore tweaker a general purpose tool. Closing this issue.
