### ISSUE TITLE
[Bug] no oregen at all

### ISSUE THREAD

**Issue by Petrisis** [EwyBoy/OreTweaker#32]
**Minecraft Version**
> 1.16.5

**Forge Version**
> 36.2.2

**Mod Version**
> 2.5.1

**Modpack & Version**
> [Crashed on Gyrnolia (CurseForge) 0.7.5](https://www.curseforge.com/minecraft/modpacks/crashed-on-gyrnolia)
_(you have to update oretweaker in this version of the pack to get the error occuring)_

**Describe the bug**
> no specified ores generate at all. the world consists of stone and features by other generators like quark

**How to reproduce**
> this error occurs to me when i update OreTweaker from 2.3.1 to 2.5.1 in my modpack "Crashed on Gyrnolia" (see above). this even happens if OreTweaker's config files are completely deleted or reinstalled.
furthermore all entries in every single file of the data folder gets multiplied. i have [this paste which shows before](https://gist.github.com/Petrisis/45fb0ea4ec6d4c264c0144dfda656d2c) and [this paste which shows after a world generation](https://gist.github.com/Petrisis/68e4b4f92901e37be7d28923555262e7). this continues each time a world generates

**Screenshots / Images**
> you can probably imagine a world containing only minecraft:stone :P

**Comment by EwyBoy** [comment]
The auto updater to the new v2 data structure does not always work in all cases. In rare cases like this you have to delete the entire `config/oretweaker` folder and restart the game. You can backup your old `oretweaker.json` by moving the `config/oretweaker/backup` folder outside the `config/oretweaker` before deleting it.

The new v2 data structure will then generate properly and you can tweak the files again. Not to much to fix here cause the auto updater was made to help convert from the v1 data structure to the new v2 data structure. Hard to say why it breaks in this case and hard to replicate so doubt it will be fixed.

**Comment by Petrisis** [comment]
i'm sorry but i have to insist on this..
like i said in the original:
> this even happens if OreTweaker's config files are completely deleted or reinstalled.

just tried it again: 
i. modpack on old version: i delete oretweaker config folder
ii. update oretweaker
iii. launch modpack, generate world
and its **stone** + vinteum from Mana and Artifice + Quark Features
the generated files in `data` look fine but they don't work!

example of `iron_ore.json` which autogenerated:
```
{
  "oreConfig": [
    {
      "ore": "minecraft:iron_ore",
      "filler": "minecraft:stone",
      "minY": 1,
      "maxY": 64,
      "maxVeinSize": 8,
      "spawnRate": 20.0,
      "biomeBlacklist": [],
      "biomeWhitelist": []
    }
  ]
}
```

**Comment by EwyBoy** [comment]
Just tested it with your pack and found a way to fix it.

1. Delete the old `OreTweaker-1.16.5-2.3.1.jar`
2. Delete the config folder `config/oretweaker`
3. Install the new `OreTweaker-1.16.5-2.5.1.jar`
4. Run Minecraft and create a new world.

Works just fine.

![2021-09-14_12 56 22](https://user-images.githubusercontent.com/5883716/133245501-5190a6ba-3a99-4a3b-9d7b-9141e3589dee.png)
