### ISSUE TITLE
[Compatibility] Medieval Craft

### ISSUE THREAD

**Issue by ThanEEpic** [EwyBoy/OreTweaker#35]
**Name of mod you want compatibility with?**
Medieval Craft

**Is your compatibility request related to a problem?**
This mod has no config and I only want one version of copper and tin in my pack.

**Describe the solution you'd like**
I just want the ability to disable the generation of these trash looking ores.

**Additional Notes**
Also yes, they named their tin ore as tin ingot.

![copperremoval](https://user-images.githubusercontent.com/28547766/134597437-93cbcacf-64b7-4d0f-bfdb-8cd3b94cb667.PNG)
![tinremoval](https://user-images.githubusercontent.com/28547766/134597440-94ef82e2-356d-41fb-84fc-fa703f093eef.PNG)
Thanks!

**Comment by EwyBoy** [comment]
The mod [Medieval Craft](https://www.curseforge.com/minecraft/mc-mods/franciscofunari) is a [MCrator ](https://mcreator.net/) mod _(program used by idiots who can't code)_.  

As long as the mod is made in MCrator I can't do anything with its world gen or ugly looking ores.  
Tell the creator to learn to code, mark his mod as a MCrator mod on Curseforge and add a config to turn of his ores.

I am sorry but there is nothing I can do for you when the mod is crated using [MCrator ](https://mcreator.net/).

**Comment by ThanEEpic** [comment]
Hahaha no worries! Thanks anyways!

**Comment by EwyBoy** [comment]
Sorry for your trouble.

**Comment by ThanEEpic** [comment]
Nah it's not your fault. At this point I may just code out his entire mod for him since he can't seem to make a config. Have a good one!
