### ISSUE TITLE
[Feature] A way to prevent ores from replacing stone variants

### ISSUE THREAD

**Issue by Thombias** [EwyBoy/OreTweaker#36]
**Is your feature request related to a problem?**
So i want to increase a few spawn rates of certain ores but the mod keeps on replacing stone variants like the Aridrock or the Limestone found in the Darker Depths mod. I specifically want to avoid ores with the vanilla stone texture generating inside or next to stone variants that have completely different textures than the vanilla stone. Unfortunately putting in the cave biomes in the biome blacklist doesn't do anything, but i believe that's because they're cave biomes using the CaveBiomeAPI and the mod doesn't know how to deal with that.

**Describe the solution you'd like**
I'm not a modder, but i believe the mod doesn't only replace minecraft:stone when it is set as the filler, but rather it uses any stone blocks that use the "minecraft:base_stone_overworld" block tag. The solution to this problem i thought of would be to add a way to tell the mod to explicitly only replace the block that uses the exact ID written in the filler section of the file, completely ignoring all block and item tags.

**Describe alternatives you've considered**
The alternative i've thought of would be to make the mod detect CaveBiomeAPI cave biomes so we can simply use the biome whitelist and blacklist to prevent replacing stone variants, but i don't know how hard it would be to implement that.

**Additional context**
No additional context available, i think.

**Comment by EwyBoy** [comment]
This has been implemented for Ore Tweaker 3.
