### ISSUE TITLE
MaxY Value is not acting. (terraforged used)

### ISSUE THREAD

**Issue by SaveTheJohnDoe** [EwyBoy/OreTweaker#39]
###### **Minecraft Version**
> 1.16.5

###### **Forge Version**
> 36.2.6

###### **Mod Version**
> 2.6.0

###### **Describe the bug**
> MaxY doesn't seem to be doing anything. MinY works.

###### **How to reproduce**
> Check if MaxY works for a custom config. My config below (also used the same config with iron ore - note that ore textures are custom but it's just the 2 ores in the picture):

```
{
  "oreConfig": [
    {
      "ore": "minecraft:coal_ore",
      "filler": "minecraft:stone",
      "minY": 16,
      "maxY": 48,
      "maxVeinSize": 32,
      "spawnRate": 2.0,
      "biomeWhitelist": ["minecraft:plains"],
      "biomeBlacklist": []
    }
  ]
}
```

###### **Link to [crashlog](https://gist.github.com/)** *[If Applicable]*
> [https://pastebin.com/0CAaaNTh](https://pastebin.com/0CAaaNTh)

###### **Screenshots / Images**
> ![image](https://user-images.githubusercontent.com/76874735/142415458-42633a26-db10-4aa4-917d-4e4be1d3cb9c.png)

**Comment by SaveTheJohnDoe** [comment]
![image](https://user-images.githubusercontent.com/76874735/142417361-fd11d4ba-3f5b-4053-8f1f-5579f1fc8830.png)
Also happens with 'Default' world setting (non-terraforged)

**Comment by EwyBoy** [comment]
Might have found the issue. Working on a fix right now, I update this thread when fixed.

**Comment by EwyBoy** [comment]
I thought I found the issue but after extensive testing both inside my development environment and on the public build on CurseForge `OreTweaker-1.16.5-2.6.0` I have found nothing wrong.

Everything works perfectly fine and as expected.

Tested with these settings:
```json
{
  "oreConfig": [
    {
      "ore": "minecraft:coal_ore",
      "filler": "minecraft:stone",
      "minY": 28,
      "maxY": 34,
      "maxVeinSize": 16,
      "spawnRate": 10.0,
      "biomeBlacklist": [],
      "biomeWhitelist": ["minecraft:plains"]
    }
  ]
}
```

The ores generate in range of what I configured it to do. No ores generate above y-level 34 and non below 28.
![2021-11-18_15 22 43](https://user-images.githubusercontent.com/5883716/142434067-0a4a8f73-7a21-4bd6-bbb7-2273da6b4545.png)

The only thing I can see with ur config is that the `"biomeBlacklist": []` and `"biomeWhitelist": ["minecraft:plains"]` are in the wrong order, not sure if that matters (it should not).

Not sure if you got any other ores interfering with the TopSolidRange() settings for how ores spawn in range.
Try remove the terraforged mod entirely and create a brand new world with my settings from above.

**Comment by SaveTheJohnDoe** [comment]
Can confirm it's a terraforged issue related to what you posted on the Discord - https://github.com/TerraForged/TerraForged/blob/dcbefa931c5e9b16e6fbc6b333f3dd1bce27dc3c/src/main/java/com/terraforged/mod/data/gen/feature/Ores.java#L56 - Closing the issue as not oretweker related (but if you ever find a way to bypass that TF code please ping me on Discord <3)

**Comment by SaveTheJohnDoe** [comment]
See Terraforged settings - https://github.com/TerraForged/tracker/issues/166
