### ISSUE TITLE
[Bug] Ore not generating in other dimensions

### ISSUE THREAD

**Issue by MysticAura** [EwyBoy/OreTweaker#4]
MC : 1.10.2
Forge: 2121
Mod Version: OreTweaker-1.0.2-1.10.2

Issue: Ore not generating in other dimensions (deep dark or rftools dimensions) Is there any way to whitelist dimensions? 

Situation: I've disabled vanilla iron gen in your configs, and added my own custom numbers. It spawns perfectly in the overworld per my specifications but other dimensions that are supposed to spawn iron ore, spawns none. If your mod is unable to control and spawn ores in other dimensions, then shouldn't those dimensions just go back to their default gen?

**Comment by rgtexa** [comment]
I'm experiencing this same issue in 1.12.2 with Forge 2571 and Ore Tweaker 1.0.2. For example, I've modified the gold and diamond ore generation, but these ores no longer generate in the Aroma1997 Mining World dimension.
