### ISSUE TITLE
[Bug] Not Working on Forge Server

### ISSUE THREAD

**Issue by RAEK0** [EwyBoy/OreTweaker#40]
###### **Minecraft Version**
> 1.16.5

###### **Forge Version**
> 1.16.5-36.2.0

###### **Mod Version**
> 1.16.5-2.5.1

###### **Describe the bug**
> Ore generation working perfectly in SinglePlayer but as soon as the Mod is added to the Server no Ore's will spawn at all

###### **How to reproduce**
> Install Mod on Server - generate World

**Comment by RAEK0** [comment]
Just read a lot in the previous Bug reports and found a comment with the explained 2.6 patch for the exact same issue. 
after replacing the Mod with the 2.6 version and deleting the old config it works just fine! 
Thank you!

**Comment by EwyBoy** [comment]
I was just gonna tell you to update. Just noticed the outdated version with the bug I just fixed. 👍
