### ISSUE TITLE
[Feature] Multiple Ores per Vein

### ISSUE THREAD

**Issue by 77wisher77** [EwyBoy/OreTweaker#43]
**Is your feature request related to a problem?**
Only **one** ore can be set per vein

**Describe the solution you'd like**
Being allowed to specify **multiple** ores,  like `Iron Ore`, `Dense Iron Ore`. Preferably with additional `weight` values for determining how likely each ore can be in a given vein
e.g.
```
{

  "ore": {

    {
      "name": "minecraft:gold_ore",
      "wieght": 85
    },
    {
      "name": "minecraft:diamond_ore",
      "wieght": 15
    }

  }

}
```

**Describe alternatives you've considered**
Currently the only alternative is having different entries spawning the ores separately. Which means they won't be in the same vein

**Additional context**
Sometimes we may want ores spawning together for thematic reasons, e.g. a modpack may want iron and copper found together. This feature could help give extra themes/lore to modpacks and cues/hints for players experiencing these configurations

**Comment by EwyBoy** [comment]
I like this, will look into adding all of your Feature Requests in the next big update.
I usually bundle up huge changes into a single update when changes will alter the `.json` files and could break it for other packs relying on the mod.

**Comment by EwyBoy** [comment]
Moved all feature requests to Discussions: https://github.com/EwyBoy/OreTweaker/discussions/65
