### ISSUE TITLE
[Feature] Different Vein Shapes

### ISSUE THREAD

**Issue by 77wisher77** [EwyBoy/OreTweaker#44]
**Is your feature request related to a problem?**
There is only one way of generating veins

**Describe the solution you'd like**
Different patterns of ore spawning such as:

- **Centered distribution**
  - Like Lapis Lazuli in vanilla, where most of the ore spawns at the center (or maybe a configurable position) and peters out further from that spot. Stopping completely at the min/max heights
- **Spheres/Ellipses**
  - So we can make boulders, discs, and/or oval shapes of ore spawning. Discs/planes could be great for making layers in the ground simulating things like crusts. While boulders are an aesthetically cool shape which could fit rock themes well
  - Plates/Cylinders is a better way to describe the axial plane idea, round shapes with flat top/bottoms, optional tapering would be nice (possibly consolidates spheres/ellipses/discs into one pattern, just different radius1, radius2, height, true/false tapering). 
- **Geodes**
  - Imperfect ellipse shapes which have a crust (small variations in height/width to give a natural look, also further differentiates it from the above idea)
  - Having a crust makes for some cool encounters, you could for example always surround an ore with lava, or surround ores with obsidian, or surround liquids with solid blocks, creating underground pockets
  - this would require picking a crust material separate to the ore and filler
- **Fractal**
  - gaps between ores in a fractal like pattern. Similar to normal veins but spread out over a larger area with filler inbetween the ores. 
- Other possible ideas are things like _trees_ (pick the trunk/leaves, spawns on top block between min/max height), _decorations_ like plants/blocks in 1x1 that spawn on the top (filler, only if one is found, like grass) block between a height range

**Describe alternatives you've considered**
There's not any alternatives that I have found in `1.16`

**Additional context**
here's some screenshots with geodes and discs/planes

[Mostly Discs, some are sliced in the walls](https://i.imgur.com/oaBJnxL.png)

[Some geodes in this one, some are cut in half](https://i.imgur.com/CAil5Qi.png)

**Comment by andrewminer** [comment]
I'd add Railcraft's "cloud" to this.  Dense core with less and less ore toward the outsides.  Plus, the ability to specify some kind of "marker" up above (e.g., a boulder which pieces of the relevant ore, or a certain kind of flower planted in a dense bunch).

**Comment by tungstonminer** [comment]
I'd add "spouts" to this list.  These are pretty much the same thing as the original BuildCraft oil wells.  It starts with a geode shape deep underground with a vertical shaft up to the surface.  The liquid fills the geode and the shaft, and extends upwards to form a tall spout above ground.

**Comment by EwyBoy** [comment]
Moving all feature request to discussions:
https://github.com/EwyBoy/OreTweaker/discussions/64
