### ISSUE TITLE
[Feature] Dimension Whitelist/Blacklist

### ISSUE THREAD

**Issue by 77wisher77** [EwyBoy/OreTweaker#45]
**Is your feature request related to a problem?**
No way to control which dimensions ores spawn in. Mods like mystcraft, immersive portals (dimension stacking feature) provide additional dimensions, with varying biomes where different rules for generation is desirable

**Describe the solution you'd like**
A whitelist and blacklist for dimension (ids? is it still dimension ids?). Sometimes we can have odd things like end-stone in non end biomes. Being able to deny or allow the ores to spawn here would be useful

for example we could have different ores spawn in different overworld like dimensions, or at different rates/sizes. E.g. maybe only iron in the main overworld, and only coal in another overworld like dimension. Or more abundant ores in other dimensions but not the overworld

These possibilities would greatly help multi-dimensional modpacks

**Describe alternatives you've considered**
The biome whitelist/blacklist helps a little. But can't be used in every situation effectively

**Additional context**

**Comment by EwyBoy** [comment]
I can add a field for `DimensionType` in the config. I can see why this is useful.

**Comment by EwyBoy** [comment]
I looked into this and they way Minecraft does this now in newer versions of Minecraft is to actually use biomes for the dimensions. There is no longer checks that can be done in the biome builder when populating the world with ores that allow me to grab the dimension type from the current level.

The new standard for this is now to use example: `minecraft:overworld` or use a biome dictionary type such as `OVERWORLD` that includes all biomes in the overworld. Same goes for the other dimensions. It kinda sucks but its not really something I can fix easily..
