### ISSUE TITLE
[Quesation] Replace multiple block types

### ISSUE THREAD

**Issue by JasonTGorman** [EwyBoy/OreTweaker#46]
I have 2 questions:

1. When an ore vein is replacing minecraft:stone, it stops when it comes to a dirt block.  (I haven't checked for gravel, but I suspect it will generate similar results as the dirt block, because the gravel block isn't covered by minecraft:stone.  But I haven't checked. this yet.)  I have searched through the wiki but I cannot see a way to tell a single ore config to replace both minecraft:stone and minecraft:dirt blocks.  I can configure 2 configs, the first to replace stone and the second to replace dirt, but then I will still have the dirt blocks existing in the veins replacing stone blocks.

2. I would like to create a configuration to replace all bedrock blocks between layers 2 - 5 into a smorgasbord of ores, however similar to my first question, I haven't worked out how to put multiple replacement clock types into a single configuration.  For this solution multiple configuration can work because the veins don't have to be continuous, but I was wondering if it was possible to do this in a single configuration.

**Comment by EwyBoy** [comment]
I am currently rewriting the mod for Minecraft 1.18 and this will fix this issue.
Right now you cannot define more then one specific block to be replaced. It is also not using `Tags`. So `minecraft:stone` is just regular stone, no other variants.

The reason I have not patched this is that changing this is hard without breaking backwards compatibility is very hard. Currently a lot of 1.16 packs depending on the current format. After I am done porting to 1.18 I will go back to 1.16 and look into creating a new custom format you have to enable to use these features.

Best approach right now is to have multiple entries for the same thing where it is possible.
