### ISSUE TITLE
[Compatibility] Tinkers Construct, Mekanism, Immersive Engineering, Create

### ISSUE THREAD

**Issue by Sasha0164** [EwyBoy/OreTweaker#47]
**Name of mod you want compatibility with?**
Tinkers Construct, Mekanism, Immersive Engineering, Create

**Is your compatibility request related to a problem?**
I am creating a modpack and I did not like the presence of a huge number of different types of the same ore, and I would like to be able to remove them

**Describe the solution you'd like**
Removing different types of the same ore

**Additional context**
-

**Comment by EwyBoy** [comment]
I think all of these mods can be disabled within their own config files.
Open the tinkers construct config and simply disable the ores and generate new ores using oretweaker.

**Comment by EwyBoy** [comment]
Decided against doing compatibility requests and instead make ore tweaker a general purpose tool. Closing this issue.
