### ISSUE TITLE
【bug】The latest version incorrectly generates Overworld minerals in the Nether

### ISSUE THREAD

**Issue by blood789** [EwyBoy/OreTweaker#49]
The latest version incorrectly generates Overworld minerals in the Nether，
For example, coal mines, copper mines..........

ver:1.18.1

**Comment by EwyBoy** [comment]
I have done some testing and have not been able to replicate this.
The mod is using the `STONE_ORE_REPLACEABLES` tag. Other mods can modify this tag.
So most likely there is another mod in your modpack adding neterrack or some other nether block to the `STONE_ORE_REPLACEABLES` tag table. Therefore allowing the ores to spawn in the nether.

You can fix this by changing the filler for your ores from `STONE_ORE_REPLACEABLES` to `"minecraft:stone",
    "minecraft:granite",
    "minecraft:diorite",
    "minecraft:andesite"`

**Comment by EwyBoy** [comment]
It could also happen because some mod spawn either Stone, granite, diorite or andesite in the nether. In that case slap a `OVERWORLD` into the `biomeWhitelist`.`

I am pushing an update to fix this so all ores comes with a dimension whitelist already set.

**Comment by EwyBoy** [comment]
https://www.curseforge.com/minecraft/mc-mods/ore-tweaker/files/3622582
