### ISSUE TITLE
[Compatibility] Mekanism

### ISSUE THREAD

**Issue by Baima-Rafael** [EwyBoy/OreTweaker#50]
**Name of mod you want compatibility with?**
Mekanism

**Is your compatibility request related to a problem?**
Not remove the ores, even that i use the .json in templates

**Describe the solution you'd like**
I think the script that have in the page "Disabling Ore Generation" would good if function for the all ores the all mods (i know this is a little bit difficult, but would is much good) OBS: I'm not a programmer, i'm a simple player

**Additional context**
I making a modpack for i played, and i want the remove all the ores, because i want to put difficulty, but the script that have in the page "Disabling Ore Generation" no function for the ores the mekanism

**Comment by EwyBoy** [comment]
Decided against doing compatibility requests and instead make ore tweaker a general purpose tool. Closing this issue.
