### ISSUE TITLE
[Compatibility] MOD-NAME

### ISSUE THREAD

**Issue by LILL097** [EwyBoy/OreTweaker#51]
**Name of mod you want compatibility with?**
Fun Ores

**Is your compatibility request related to a problem?**
I own a modpack, i needed an ore which could give ghast tears and blaze rods, the only one i found was fun ores, but i can't stop the other ores from spawning using your mod.

**Describe the solution you'd like**
I'd like the mod to be able to deactivate those kind of ore gen. It would also be good to know what are the min and max values i can give to each parameter, like which number means 100% spawn rate; for example, if i want to remove some kind of copper from a mod, i'll replace it with another's using it as filler and the one i like as ore to spawn with 100% probability on the other one.

**Comment by EwyBoy** [comment]
Decided against doing compatibility requests and instead make ore tweaker a general purpose tool. Closing this issue.
