### ISSUE TITLE
[Feature] Flying Ore Veins

### ISSUE THREAD

**Issue by AJBS-alexo** [EwyBoy/OreTweaker#52]
###### **Minecraft Version**
> 1.16.5

###### **Forge Version**
> 1.16.5-forge-36.2.23

###### **Mod Version**
> OreTweaker-1.16.5-2.6.0

###### **Describe the bug**
> I recently started tweaking ores with OreTweaker but when I wrote this JSON file it didn't worked as intended (nothing is generated)
{
  "oreConfig": [
    {
      "ore": "minecraft:stone",
      "filler": "minecraft:air",
      "minY": 200,
      "maxY": 250,
      "maxVeinSize": 32,
      "spawnRate": 5.0,
      "biomeBlacklist": [],
      "biomeWhitelist": ["OVERWORLD"]
    }
  ]
}
normally this is meant to generate stone patches high in the sky but it seems there is a y-level cap for the mod to generate ores (I tried with minY=1 and maxY=250 and the highest patch found was at y=105

###### **How to reproduce**
> Just type the code in a JSON file and run the game

###### **Link to [crashlog](https://gist.github.com/)** *[If Applicable]*
> There is no crash-log

###### **Screenshots / Images**
> 
![2022-02-24_11 22 46](https://user-images.githubusercontent.com/100349698/155505987-6a7564bd-e7fa-4990-9264-17d2813b7be5.png)

**Comment by EwyBoy** [comment]
Its a limitation to the vanilla Minecraft world generator they made for performance reasons.
For them there is no reason to attempt to generate a ore in a place where there is no other world generation going on (the sky).
Therefor you are currently unable to generate any ores floating high up in the sky..
I can look into creating my own custom generator that would allow you to do this but this might take a little while to get fixed.

**Comment by AJBS-alexo** [comment]
It would be so helpful to be able to generate "clouds" made out of ores in the sky, early thanks if you decide to create it

**Comment by EwyBoy** [comment]
Moved to discussions: https://github.com/EwyBoy/OreTweaker/discussions/66
