### ISSUE TITLE
[Compatibility] MOD-NAME:THE AFTERLIGHT want for the support of disabling the ores of this mod

### ISSUE THREAD

**Issue by ScientistMr** [EwyBoy/OreTweaker#53]
**Name of mod you want compatibility with?**
Mod name.

**Is your compatibility request related to a problem?**

**Describe the solution you'd like**
A clear and concise description of what you want the compatibility to accomplish.

**Additional context**
Add any other context or screenshots about the compatibility request here.

**Comment by EwyBoy** [comment]
Decided against doing compatibility requests and instead make ore tweaker a general purpose tool. Closing this issue.
