### ISSUE TITLE
[Bug] Some sort of watchdog error, most likely terraforged error

### ISSUE THREAD

**Issue by rakostep** [EwyBoy/OreTweaker#54]
###### **Minecraft Version**
1.16.5

###### **Forge Version**
36.2.4

###### **Mod Version**
OreTweaker-1.16.5-2.6.0

###### **Describe the bug**
Crashes upon generating a new singleplayer world

###### **How to reproduce**
Custom config with iron ore to generate on higher y coordinates + terraforged + create with strata decorator on

_The said config:_

> {
>   "oreConfig": [
>     {
>       "ore": "minecraft:iron_ore",
>       "filler": "minecraft:stone",
>       "minY": 1,
>       "maxY": 64,
>       "maxVeinSize": 4,
>       "spawnRate": 13.0,
>       "biomeBlacklist": [],
>       "biomeWhitelist": []
>     },
>     {
>       "ore": "minecraft:iron_ore",
>       "filler": "minecraft:stone",
>       "minY": 153,
>       "maxY": 250,
>       "maxVeinSize": 21,
>       "spawnRate": 48.0,
>       "biomeBlacklist": [],
>       "biomeWhitelist": ["MOUNTAIN", "WASTELAND", "PLAINS", "FOREST", "SNOWY"]
>     }
>   ]
> }
> 

###### **Link to [crashlog](https://gist.github.com/)** *[If Applicable]*

[crashreport](https://gist.github.com/rakostep/0721c9223ce9b3f7bbae4bfba8d8e228)

**Comment by rakostep** [comment]
Oh uhhh I tested it on the "vanilla mode" of terraforged and it seems to work there but the strata decorator is off.

**Comment by EwyBoy** [comment]
It's kinda a known issue. Ore Tweaker does not always play nice with other mods that heavily change how the world works. It's really not anything I can do to fix this easily unfortunately..

My best advice is to try different settings until you perhaps find something that magically works.

-Ewy

**Comment by rakostep** [comment]
oh thanks for the fast response, I'll see what I can do.
