### ISSUE TITLE
[Bug] Crash on Create World

### ISSUE THREAD

**Issue by AbieTheFishman** [EwyBoy/OreTweaker#56]
###### **Minecraft Version**
Minecraft Version: 1.18.1

###### **Forge Version**
Forge: net.minecraftforge:39.1.2

###### **Mod Version**
OreTweaker-1.18.1-3.0.2.jar

###### **Describe the bug**
Crash on World Create

###### **How to reproduce**
Create a new world

###### **Link to [crashlog](https://gist.github.com/)** *[If Applicable]*
[crash-2022-04-04_13.24.49-client.txt](https://github.com/EwyBoy/OreTweaker/files/8411956/crash-2022-04-04_13.24.49-client.txt)
> Type here

###### **Screenshots / Images**
> Ctrl + V here

**Comment by EwyBoy** [comment]
Have you edited any of the files?

**Comment by AbieTheFishman** [comment]
Also datapack error on loading old world

[latest.log](https://github.com/EwyBoy/OreTweaker/files/8411961/latest.log)

**Comment by AbieTheFishman** [comment]
Some of the config files?

**Comment by EwyBoy** [comment]
> Some of the config files?

Yes any of the files inside `config/oretweaker/data` 📂

**Comment by AbieTheFishman** [comment]
Yes

**Comment by EwyBoy** [comment]
Looks like you messed up somewhere. You have an null error on one of your ores.
You can send me a link to some of the files and I can look into it for you.

**Comment by AbieTheFishman** [comment]
Should I try to replace the files in data with the defaults in templates?

**Comment by EwyBoy** [comment]
You can make a copy of your `config/oretweaker/data` 📂
Then delete the entire `oretweaker` 📂 inside `config` 📂 and restart Minecraft.
It will regenerate all the default files as they should be.

And when you start editing the files. Edit one file at the time and run a test to see if it works. Easier for you to figure out when something goes wrong and where the error is.

**Comment by AbieTheFishman** [comment]
Yep it was one the json files. Had an extra comma.

Thanks

**Comment by EwyBoy** [comment]
Np, working on a system to detect these extra commas etc and fix it before it breaks everything.
Sorry for the trouble 🥳

**Comment by AbieTheFishman** [comment]
No, thank you
