### ISSUE TITLE
[Feature] Remove large ore veins

### ISSUE THREAD

**Issue by Henrique143** [EwyBoy/OreTweaker#58]
###### **Minecraft Version**
> 1.18.2

###### **Forge Version**
> forge-1.18.2-40.0.40

###### **Mod Version**
> OreTweaker-1.18.2-3.1.0

###### **Describe the bug**
> Using the "remove_everything.json" config to remove all ore generation does not remove the large ore veins introduced in 1.18 (https://minecraft.fandom.com/wiki/Ore_vein)

###### **How to reproduce**
> Delete all the files inside the "../config/oretweaker/data/" folder and move the "remove_everything.json" from the template folder to the data folder. Create a new world.

###### **Link to [crashlog](https://gist.github.com/)** *[If Applicable]*
> Type here

###### **Screenshots / Images**
> 
![2022-04-06_16 39 57](https://user-images.githubusercontent.com/16382059/162057045-95cb70f8-79fc-4011-8780-60001d302b45.png)
![2022-04-06_16 40 48](https://user-images.githubusercontent.com/16382059/162057094-647bfa81-e9df-4a44-8317-3b862b943e96.png)

**Comment by EwyBoy** [comment]
They are currently almost impossible to remove cause they are not coded as a world generation feature but instead hardcoded right into the terrain generator.
I have yet to figure out a way to disable them 😓

**Comment by EwyBoy** [comment]
Fixed in Ore Tweaker v3.3.0
1.18.1 - https://www.curseforge.com/minecraft/mc-mods/ore-tweaker/files/3758506  
1.18.2 - https://www.curseforge.com/minecraft/mc-mods/ore-tweaker/files/3758507
