### ISSUE TITLE
[Feature] Multiple entries for Filler Block field

### ISSUE THREAD

**Issue by Steamoonkie** [EwyBoy/OreTweaker#59]
**Is your feature request related to a problem?**
Doubt it is considered problem. Rather feature request.

**Describe the solution you'd like**
Add possibility to make filler block/s json array **["minecraft:stone", "minecraft:dirt"] as it is done with BiomeBlacklist/Whitelist

**Describe alternatives you've considered**
I tried to do it manually , error appeared for syntax. Expected String (normal behavior), I tried Array :)

**Additional context**

**Comment by EwyBoy** [comment]
The mod already on paper support arrays for setting multiple filler blocks. In the case that this does not work its a bug.
Can you send me the minecraft version and the mod version you are using?

**Comment by Steamoonkie** [comment]
**MC Version:** 1.16.5
**Forge Version:** 36.2.33
**Mod Version:** 1.16.5-2.7.0
