### ISSUE TITLE
[Request] Biome Specific Spawns

### ISSUE THREAD

**Issue by ghost** [EwyBoy/OreTweaker#6]
Would it be possible to add a feature to restrict ore spawns based on a list of biomes given in a new config option?

**Comment by EwyBoy** [comment]
Yeah, I am gonna rework the mod when I get the time, gonna fix biome / dimension specific spawn option as well as reworking how the config looks.

**Comment by EwyBoy** [comment]
This can be found in https://www.curseforge.com/minecraft/mc-mods/ore-tweaker the 1.16 version. 
Sorry this did not happen 4 years ago.
