### ISSUE TITLE
[Bug] Crash when there are non-JSON files in the data directory

### ISSUE THREAD

**Issue by tungstonminer** [EwyBoy/OreTweaker#60]
###### **Minecraft Version**

1.18.1

###### **Forge Version**

39.1.0

###### **Mod Version**

3.0.2

###### **Describe the bug**

If any non-JSON files are present in the `config/oretweaker/data` directory, it will attempt to read them as though they were regular JSON files.  This fails, and causes the game to fail to load.

###### **How to reproduce**

Place any non-JSON file in the `data` directory.

###### **Link to [crashlog](https://gist.github.com/)** *[If Applicable]*

See [Discord chat](https://discord.com/channels/305535757441826817/390890978980003840/965624730826715178).

###### **Screenshots / Images**

n/a

**Comment by EwyBoy** [comment]
Fixed in:  
- v1.16.5 - 2.7.1
- v1.17.1 - 2.6.1
- v1.18.1 -  3.3.0
- v1.18.2 - 3.3.0
