### ISSUE TITLE
[Feature] Allow generating wild crops

### ISSUE THREAD

**Issue by tungstonminer** [EwyBoy/OreTweaker#62]
**Is your feature request related to a problem?**

I often create modpacks which introduce new crops.  They almost always have various odd ways to get the original seeds, though (e.g., in a loot chest, trade with a villager, seeds from from tall grass, etc.).  Instead, I'd love to have the ability to specify little clumps of them which appear in the wild for players to stumble across.

**Describe the solution you'd like**

I'd like the ability to specify a `WILD_FARM` distribution which converts a small patch of `filler` blocks which are open to the sky into farmland with a single dot of water in the center.  Above these, the crops specified by `ore` would be placed.  The default `filler` should be grass or dirt.

**Describe alternatives you've considered**

I've never been able to come up with another way to accomplish something similar.

**Additional context**

None.

**Comment by EwyBoy** [comment]
Although its a very cool proposal its does not fit this mod at all and its not how ore tweaker is written to function.
In the current state of ore tweaker this would be impossible. Sorry
