### ISSUE TITLE
Not working with modded ores

### ISSUE THREAD

**Issue by Dylan0507** [EwyBoy/OreTweaker#7]
I am spelling all of the names correctly in the config. Here is what i did:
1. Copy & pasted a box of code (By box i mean code for 1 ore)
2. Made sure i skipped 2 lines in between each box of code.
3. Replaced "Redstone" with the other names like "Copper", "Tin", and "Silicon" each time. (I am using the galacticraft mod)
4. Did the same with the settings
5. saved my progress
6. Booted up minecraft (forge)
7. Used world stripper and only the vanilla ores seemed bigger & higher
8. Closed Minecraft and looked for coding errors
9. Minecraft kept bugging the scripts
Please tell me how to fix this down in the comments.

**Comment by EwyBoy** [comment]
Ore Tweaker does not have script support nor can you tweak ores from other mods but the vanilla ores.
As of right now I don't have the time to add support for said stuff above. I am sorry.
-Ewy

**Comment by Dylan0507** [comment]
Its ok. I have to admit though, it is a pretty good mod for "normal" survival. At least vanilla ores can be easy now, right?

**Comment by EwyBoy** [comment]
Yes, sorry for the inconvenience. Should work well for vanilla.
