### ISSUE TITLE
[Compatibility] MOD-NAME

### ISSUE THREAD

**Issue by wuggyfoot** [EwyBoy/OreTweaker#81]
FTB Industrial Contraptions

**Comment by EwyBoy** [comment]
I don't do compatibility requests anymore. Don't have the time, sorry.

**Comment by DerCommander323** [comment]
Its already supported though? Definetely works fine for me, removing adding and changing.

**Comment by EwyBoy** [comment]
> Its already supported though? Definetely works fine for me, removing adding and changing.

Ore Tweaker works with most mods. So it should indeed work.
