### ISSUE TITLE
Gives me an error message when I change the spawnrates of ores.

### ISSUE THREAD

**Issue by stmjs** [EwyBoy/OreTweaker#89]
###### **Minecraft Version**
1.16.5

###### **Forge Version**
36.2.34
###### **Mod Version**
2.7.1

###### **Describe the bug**
When I change the spawnRate values, I am met with an error that says "Ore Tweaker (oretweaker) encountered an error during the complete event phase", and then "com.google.gson.JsonSyntaxException:"

###### **How to reproduce**
Download all applicable versions and launch them in order to create the folder "C:\Users\*****\AppData\Roaming\.minecraft\config\oretweaker". For coal ore, diamond ore, gold ore and iron ore, increase the values for "spawnRate", and then relaunch the build. Will be met with an error as described.

###### **Link to [crashlog](https://gist.github.com/)** *[If Applicable]*
https://gist.github.com/stmjs/6c469189ab2d4cb1a6dd1a1ffd742d45

###### **Screenshots / Images**
![image](https://user-images.githubusercontent.com/123350236/213973157-1dd631b0-ee0e-4e4c-9831-f24543aff87a.png)

**Comment by EwyBoy** [comment]
com.google.gson.JsonSyntaxException means you did something wrong in the json file.
I suggest you use get a propper text editor for editing json files. You can read more here:
https://github.com/EwyBoy/OreTweaker/wiki/Validating-JSON-File

Most likely a missing , or { or a [ etc..
