### ISSUE TITLE
[Compatibility] Gems and Jewels

### ISSUE THREAD

**Issue by AndyCat1811** [EwyBoy/OreTweaker#92]
Hi!  It would be nice to have a compatibility with the mod Gems and Jewels!  It adds tons of ores but the config doesn't work so adding Terralith or any other mod that creates cave biomes makes the ores that are biome-specific almost absent.
[https://www.curseforge.com/minecraft/mc-mods/gems-jewels](url)

**Comment by AndyCat1811** [comment]
It didn't work at first so I assumed since there was a compatibility request thing that it wasn't compatible but I figured out the problem and it was on my part, sorry!

**Comment by EwyBoy** [comment]
No problem 😅
